from DbFunctions import DbConnector

print(DbConnector.create_device(name="arduino", total=3, place="here"))
print(DbConnector.create_device(name="esp", total=3, place="here"))
print(DbConnector.delete_device(2))
print(DbConnector.edit_device(3, name="esp8266"))
print(DbConnector.create_project("second", description="2 project", link="http://amperka.ru"))
print(DbConnector.edit_project(2, link="http://amperka.ru2", archived=not True))
print(DbConnector.add_detail_to_project(1, 1, 1))
print(DbConnector.edit_details(1, 1, 4))
print(DbConnector.edit_details(1, 1, 0))
# print(DbConnector.delete_project(1))
'''print(DbConnector.add_part("esp", "new", "there", 1))
print(DbConnector.add_type("arduino"))
print(DbConnector.add_part("arduino", "new", "there2", 1))
print(DbConnector.add_proj(name="second", link="http"))
print(DbConnector.add_to_project(5, "second"))
print(DbConnector.add_to_project(2, "second"))
print(DbConnector.add_to_project(1, "second"))
print(DbConnector.get_all_types())
print(DbConnector.get_all_projects())
print(DbConnector.get_type_info("esp"))
print(DbConnector.get_part_info(1))
print(DbConnector.update_part(2, info="new info"))
print(DbConnector.update_part(1, place="new place"))
print(DbConnector.update_type("esp", "esp8266"))
print(DbConnector.update_project(1, description="updated project"))
print(DbConnector.get_project_details("test_p"))
print(DbConnector.delete_type("arduino"))
'''
